name: Build

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow_ref, github.event.pull_request.number) || github.run_id }}
  cancel-in-progress: true

jobs:
  build-package:
    name: Build ${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.CC }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - windows-2025
        mode:
          - Release
          - Debug
        CXX:
          - ""
          - clang++
        exclude:
          - os: macos-13
            CXX: clang++
          - os: macos-14
            CXX: clang++
          - os: macos-15
            CXX: clang++
          - os: windows-2022
            CXX: clang++
          - os: windows-2025
            CXX: clang++
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        env:
          CXX: ${{ matrix.CXX }}
        run: |
          cmake -B build -DCP_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
          cmake --build build --config ${{ matrix.mode }}
          cmake --build build --config ${{ matrix.mode }} --target tests
      - name: Test (windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          build\${{ matrix.mode }}\test.exe
      - name: Test
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          build/test
      - name: Plotter (windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          build\src\tools\plotter\${{ matrix.mode }}\plotter.exe 18
          build\src\tools\solver\${{ matrix.mode }}\solver.exe prove plot_18_16_xvalues_nonbipartitebeforet3_0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF.bin
      - name: Plotter
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          build/src/tools/plotter/plotter 18
          build/src/tools/solver/solver prove plot_18_16_xvalues_nonbipartitebeforet3_0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF.bin
      - name: Benchmark (Windows)
        if: ${{ matrix.mode == 'Release' && startsWith(matrix.os, 'windows') }}
        run: |
          build\src\tools\solver\${{ matrix.mode }}\solver.exe benchmark 28
      - name: Benchmark
        if: ${{ matrix.mode == 'Release' && !startsWith(matrix.os, 'windows') }}
        run: |
          build/src/tools/solver/solver benchmark 28


